### ISSUE TITLE
Unmapped ERDRI Data elements 

### ISSUE THREAD

**Issue by S2Ola** [EBISPOT/EJP-Ontology#5]
Unmapped terms in the ERDRI data elements
- [ ] geneticist
- [ ]  gynaecologist
- [ ]  Trestment   - suggestion : may be wrongly spelt term  "treatment"
- [ ]  Ante-natal
- [ ]  Neo-natal
- [ ]  Foetopathology
- [ ]  obstetrician

**Comment by brunasv** [comment]
I would map it also to this ERDRI/JRC [common data elements for Rare Disease registries ](https://eu-rd-platform.jrc.ec.europa.eu/sites/default/files/CDS/EU_RD_Platform_CDS_Final.pdf)

**Comment by brunasv** [comment]
There are many use cases started/not yet among the more than 20 ERNs. In a broader view, this EJPRD ontology could map for all needed terms for all of these registries.

**Comment by S2Ola** [comment]
@brunasv  Thank you for the feedback, it would be great if you can with use cases too, it will go along way.

**Comment by brunasv** [comment]
Also map it to the semantic model we discussed this morning (:
